---
title: "M^c^Cool People: Prof. Peadar Duignan"
mainfont: Courier Prime
---

McCool FM - Interview Transcript <br>
Maggie McCool-Prof. Peadar Duignanl, 18th February 1990, 11.00 a.m.

__Maggie M^c^Cool:__
You’re listening to McCool FM and I’m your host Maggie McCool. Today we have a very relevant guest, Professor Peadar Duignan from University College Cork. He’s the Biway’s utmost expert on the DOT, having been there himself, and a Dotter of Tartarus which I won’t hold against him. Welcome Professor Duignan.

Peadar Duignan: 
Thanks for having me. We don’t need to stand to ceremony so please feel free to call me Peadar, Maggie. Additionally, I won’t hold it against you for being a Sun of Nyxmera.

MM: Oh I do miss that Irish sass. So, we have a new opening to the DOT in the Biways, from our latest reports it appears to have opened in an underground cave under the village of Warboys, not too far from our station actually. What can you tell us about The DOT and its opening Peadar?

PD: Thanks for setting up the foundation. As many people know Tartarus is the deity of the Earth, imprisoned by Nyxmera. In essence it is the planet Earth and is symbolised with cracks and openings.Below the ground and within the Earth is the DOT, The Domain Of Tartarus. Openings to the DOT look like circular black holes where no light enters or leaves, we call these the Jaws of Tartarus. It is imperative that you never enter unless you are prepared for the environment and you’re ready to never return.

MM: Is it true that time is weird in the DOT? I heard that when you emerged no time had passed on the surface even though years had passed for you.

PD: Not quite true. When I entered the DOT I was the last on my team to pass the precipice. Just as I was entering a person came out. He didn’t look like any of my team members even though he was wearing our expedition badge. It wasn’t till he spoke did I recognise myself. I knew by his tone that the rest of my team wouldn’t… hadn’t made it out but I could also tell he had no regrets so I descended into the gullet of my deity.

MM: Wow! If I ever had the chance to go to space and properly gaze at the stars, the eyes of Nyxmera, I also think I would leap at the opportunity. We’ll get more to the details of your journey later but first can you tell us of the various dangers. The military locked down the village after DOT raiders attacked and pillaged it and then we saw some lava emerge on the surface. What other threats could possibly come from The DOT?

PD: Before I get to other threats I would like to address the DOT raiders if I may Maggie.

MM: Of course Peadar.

PD: DOT raiders are humans that live in the DOT. They are all Dotters of Tartarus as non believers do not last long. Their tools, vehicles and dwellings are bolted together from scrap and they believe in the free market.

MM: As in no economic regulation and the price of goods are based on supply and demand?

PD: That is the free market that many surface Dotters aim to benefit from. No, those in the DOT believe everything is free if you can take it. It's a brutal and sometimes cruel society down there. However, so is the environment. Everyone does what they can to survive including mutating. I saw someone with 2 heads once and another person with tentacles for arms.

MM: What causes this mutagenic effect?

PD: No one is quite sure, more research is needed. I believe it is caused by all the hazardous waste dumped into the DOT in combination with the powers bestowed by Tartarus. One of the biggest known jaws is in The Big Hole Dump yard in Kimberley, South Africa in The Coalition of African Countries. They have a special Kaiju prevention system. If they didn't, an incredibly large kaiju could surface, rivalling those in Japan.

MM: Seems there is a lot of danger in the DOT. We know DOT raiders can and have reached the surface. Instead of coming up and taking our stuff why don’t they just live up here when or if they get here?

PD: Why do capitalists extract wealth from the poor? They are good questions and I aim to find out through my studies. People grow up doing what they know. Sure Raiders could live up here and work. Sure CEOs could pay taxes and give money to charities as well. But for many people it's easier to live a hard stressful life than learn to change.

MM: And here I thought philosophy was for Gaians but as they would say, we are multitude. Aside from DOT raiders, what other dangers could we see on the surface?

PD: Well of course we could get kaiju. These are bestial creatures, generally a incredibly large version of an animal living or extinct with some kind of peculiarity. An insect kaju would be the size of a dog or cow and a cat kaiju would be the size of a bus or building. They are covered in red cracks and always have a large obsidian orb on them. Normally something weird happens around the orb, commonly something being duplicated. A common kaiju is the Scorpius, giant scorpions with an obsidian orb at the base of their two tails. They are deadly to others and themselves. I hated eating them.

MM: I’m taking it that no normal animals live down there?

PD: Not much, just small things like bugs, lizards, rats etc. Interestingly many of the kaiju seen in the DOT have normal animal counterparts down there. The relation between these two are hotly debated so I’ll leave the topic of kaiju at that for now so I don’t anger any fellow DOT researchers, we’re a fiery bunch.

MM: Very interesting, I thought I knew all there was to know about kaiju but you’ve taught me something new. Would you like to talk about your journey?

PD: Oh yes, I documented a new type of Talos. The paper just got published so I can talk about it. For those unaware a Talos, Taloes for plural, is a sentient creature consisting of minerals. They are hard to find and generally very dangerous so hard to study. We knew of exploding blobs made of lithium, large columns like Taloes made of local ores, and even one consisting of a radioactive gem that can project some sort of body.

MM: From my understanding many see these as the avatars of Tartarus. Similar to the Starvatars of Nyxmera, The Water bodies of Proteus, or the Life forms of Gaia.

PD: Indeed. Well, I discovered what I dubbed an Obsidian lava Talos. I was confused as it appeared to be a Talos made of lava and of Obsidian. It's mostly unheard of that a Talos is made from more than one mineral. Through diligent study I discovered that the lava and obsidian were one in the same. They can actively change their lava to obsidian and vice versa. They can also absorb more lava if they wish. It's remarkable.

MM: That does sound very cool. WHat do you intend to do next?

PD: I have more funding now to go on another exhibition. This time we’ll have a guard detail and a camera crew. They want us to make a documentary!

[end of excerpt]
