---
title: "PAAR: DEBT"
mainfont: Special Elite
---

MISSION <br> 
**D**RUG **E**XCHANGE on A **B**RIDGE **T**ONIGHT

**MISSION LOCATION** <br> 
█████████████████████████████ ON L’OISE (RIVER), NORTH OF THE FORMER FRENCH CAPITAL PARIS, FRANCE,  ERA (EUROPEAN AND RUSSIAN ALLIANCE)

**MISSION STARTED - MISSION CLOSED** <br> 
2004, 16TH JAN 1990 - 0345, 17TH JAN 1990

**CLIENT - CONTRACT DATE** <br> 
TAG (THE ARROWS OF GAIA)- 16TH JAN 1990

**REMARKS** <br> 


**MERCENARIES INVOLVED - CODENAMES - STATUS** <br> 
████████████████████ - VEILED NIGHTJAR - ACTIVE <br> 
████████████████████ - CRACKED BATFISH - ACTIVE <br>
████████████████████ - FLASHBANG SQUIRREL - KIA <br>
████████████████████ - SIGHTLESS TRUFFLE - ACTIVE <br>
████████████████████ - LANCED BULL - ACTIVE <br>
████████████████████ - BLINK HARE - ACTIVE <br>

In DEBT: Drug Exchange on a Bridge Tonight, our mercs decided to represent TAG, eco warriors, to purchase some of the illicit drug Holy water. They met up with the sellers from Triton & Delta on a bridge over the Oise, North of Paris.  Otto, the seller, demanded £50K rather than the agreed £40K but with some negotiation including crying by the pathetic Flashbang, the mercs managed to make the initial trade. Unfortunately, that's when the Kraken Slagger, Dross, arrived demanding all the goods. With some mind reading assisted blackmail Nuke was able to give Dross the money whilst they escaped with the Holy Water.

This led to a chase with cars, motorcycles, and speedboats along the river. With a sharp breaking of his car, Cracks flung Dross onto the team's boat, helmed by Truffle. Blink dodged a battering ram with quick shrinking, Wolf crushed a pursuing motorcyclist with reckless driving, and Midnight failed to blow up a car with a flare gun.

With Dross firing his fiery Bren LMG at Truffle, Truffle decided the only way would be to crash his boat into an upcoming bridge, flinging them both onto it. Cracks capatilised on this by crashing his car onto the bridge killing himself, Dross, and Flashbang in a fiery explosion. Truffle was flung into the river and  Cracks miraculously emerged unscathed except for a broken amulet. RIP the pathetic Flashbang.
