---
title: "M^c^Cool People: Pat"
mainfont: Courier Prime
---

McCool FM - Interview Transcript <br>
Maggie McCool-Pat, 17th June 1990, 11.00 a.m.

__Maggie M^c^Cool:__
Good morning to you all on this lovely June morning. Today on McCool people I, Maggie McCool, am joined by Pat. Good morning Pat or can I call you Paddy?

__Pat:__ 
Good morning to yourself. Paddy’s me personal name but for business it's Pat. How are you doing?

__MM:__ I’m grand, and yourself?

**P**: Grand, can’t complain.

**MM:** Brilliant. Some of our listeners may have heard of you but can you please tell us about yourself.

**P:** Gladly, I’m Pat of PUML. That stands for Pat’s Undisclosed Mercenary League. I run a mercenary group of gifted individuals. I’m here to promote our business and to announce that we are hiring.

**MM:** That must be a very interesting job but surely it is dangerous. Why would people want to join?

**P:** Well, I can’t guarantee that you’ll be loaded but you will be free to do what you want to do. If you’re primal and don’t join us the government may very well recruit you, imprison you, or experiment on you.

**MM:** Primal?

**P:** Sorry, in military speak Primal refers to those with gifts or powers from one of the Primeval Deities. I’ve seen people breathe fire like a dragon, float in the air like a jellyfish, and even someone grow back one of their two heads. Yes the job is dangerous but you can die a free and exciting death with us or live a dull imprisoned life with the government.

**MM:** Do you go on missions?

**P:** Those days are behind me now. I’m a family man and decided to take care of me daughter. I’m what’s called a handler now. I vet our clients and missions making sure I assign suitable mercs to the jobs. We only take jobs that we think will help people. Our clientele has included corporations, governments, individuals, and charities.

**MM:** Charities? Why would they need to hire mercenaries?

**P:** Sometimes they provide aid to war torn areas and we’ll be their protection detail.

**MM:** Fascinating. It sounds like you want to try to make the world a better place. Why is that?

**P:** I was just a soldier. I thought it would be an easy job with the world being at peace. Through that I found war all across the world, minor ones but any could start another world war. Truthfully that didn’t change me. I fell in love and had a daughter with me wife. So I want to make the world better for her.

**MM:** Well your wife is certainly lucky to have a catch of a man like yourself.

**P:** She’s unfortunately no longer with us. Not for a while now.

**MM:** I’m so sorry.

**MM:** On another note, what do you think of the Blondie and Scaly-man-thing-guy franchise?

**P:** It’s great fun and I'm looking forward to finally seeing the Cockroach Empress. Though, I wasn’t sure about the 2 becoming accountants in the fifth film.

**MM:** It's not the best film but it does contain some vital lore in the post credits scene. It really changed how I saw some of their previous interactions.

**P:** It beats the film where they fight the hat wearing dinosaurs from the centre of Mars. 

**MM:** Who thought a mid film genre switch into a court drama about space trade was a good idea?

[Laughing in unison]

[end of except]

