---
title: "PAAR: DELVE"
mainfont: Special Elite
---

MISSION <br> 
**TE**RRIFYING **I**NFILTRATION OF **D**UMP **Y**ARD

**MISSION LOCATION** <br> 


**MISSION STARTED - MISSION CLOSED** <br> 


**CLIENT - CONTRACT DATE** <br> 


**REMARKS** <br> 

Although coming out a month later our team spent less than a day of their time in the DOT. Could have been better but also could have been a lot worse.

**MERCENARIES INVOLVED - CODENAMES - STATUS** <br> 
████████████████████ - WOODEN SPARROW - KIA <br> 
████████████████████ - STEAM GAZELLE - ACTIVE <br>
████████████████████ - UNICORN - ACTIVE <br>

https://m-gemmell.github.io/PRIMEVAL_DEITIES/Missions/M-TIDY.html

In the last mission of Primeval Pummeling the team infiltrated a dump yard in South Africa. This is where cargo containers were dumped into the DOT. The team unwittingly stopped the Kaiju defences causing them to combat an entity consisting of 3 massive snakes combined by an obsidian orb. With mechs, a vorpal beheading, casualties, toppling a building, and a rod from god they vanquished the Python and successfully escaped. Next mission the team is off to Hong Kong to investigate an infestation of mutant Horseshoe crabs.

