project:
  type: website
editor: source
#Website
website:
  bread-crumbs: false
  favicon: /images/mccool_fm_logo.png
  page-navigation: true
  title: "M^c^Cool FM"
  description: "McCool FM"
##Navbar
  navbar:
    title: M^c^Cool FM
    logo: "images/mccool_fm_logo.png"
    collapse-below: lg
###Navbar left
    left:
      - text: "Overview"
        href: index.qmd
      - text: "1989"
        href: 1989/december/new_radio_station.qmd
      - text: "1990"
        href: 1990/january/si_senor.qmd
###Navbar right
    right:
    # List of icons: https://icons.getbootstrap.com/
      - icon: cup
        href: https://ko-fi.com/waveofinspiration
        aria-label: Ko-fi
      - icon: github
        href: https://github.com/m-gemmell/McCool_FM
        aria-label: GitHub
##Apge footer
  page-footer:
    left: |
      ![](/images/mccool_fm_logo.png){width=100}
    center: |
      [![](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K6IRLA0)
##Sidebar
  sidebar:
    - id: Overview
      title: "Overview"
      style: "floating"
      align: left
      contents:
        - href: index.qmd
    - id: year_1989
      title: "1989"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - section: December 1989
          contents:
          - href: 1989/december/new_radio_station.qmd
          - href: 1989/december/gaias_wreath.qmd
          - href: 1989/december/mccool_fm_news_dec_1989.qmd
          - href: 1989/december/primeval_deities_and_you_ep_1.qmd
          - href: 1989/december/pump_sightless_truffle.qmd
          - href: 1989/december/pump_subsonic_hydra.qmd
          - href: 1989/december/pump_flashbang_squirrel.qmd
          - href: 1989/december/pump_cracked_batfish.qmd
          - href: 1989/december/paar_green.qmd
    - id: year_1990
      title: "1990"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - section: January 1990
          contents:
          - href: 1990/january/si_senor.qmd
          - href: 1990/january/mccool_fm_news_jan_1990.qmd
          - href: 1990/january/primeval_deities_and_you_ep_2.qmd
          - href: 1990/january/mccool_people_sol.qmd
          - href: 1990/january/pump_veiled_nightjar.qmd
          - href: 1990/january/pump_flustered_turkey.qmd
          - href: 1990/january/paar_avow.qmd
        - section: February 1990
          contents:
          - href: 1990/february/warboys_dot_opening.qmd
          - href: 1990/february/boulder_os.qmd
          - href: 1990/february/mccool_fm_news_feb_1990.qmd
          - href: 1990/february/primeval_deities_and_you_ep_3.qmd
          - href: 1990/february/mccool_people_prof_peadar_duignan.qmd
          - href: 1990/february/paar_debt.qmd
          - href: 1990/february/paar_pops.qmd
        - section: March 1990
          contents:
          - href: 1990/march/pumice_construction.qmd
          - href: 1990/march/mccool_fm_news_mar_1990.qmd
          - href: 1990/march/primeval_deities_and_you_ep_4.qmd
          - href: 1990/march/mccool_people_dr_rangi_doshi.qmd
          - href: 1990/march/paar_delve.qmd
        - section: April 1990
          contents:
          - href: 1990/april/mccool_fm_news_apr_1990.qmd
          - href: 1990/april/primeval_deities_and_you_ep_5.qmd
          - href: 1990/april/mccool_people_dr_petra_pufferfish.qmd
          - href: 1990/april/paar_play.qmd
        - section: May 1990
          contents:
          - href: 1990/may/primeval_deities_and_you_ep_6.qmd
          - href: 1990/may/paar_sick.qmd
        - section: June 1990
          contents:
          - href: 1990/june/basmthgvtrfos.qmd
          - href: 1990/june/mccool_people_pat.qmd
        - section: July 1990
          contents:
          - href: 1990/july/mccool_fm_news_jul_1990.qmd
          - href: 1990/july/primeval_deities_and_you_ep_8.qmd
        - section: August 1990
          contents:
          - href: 1990\august\hyperborean_ice_cream.qmd
          - href: 1990/august/mccool_fm_news_aug_1990.qmd
          - href: 1990/august/primeval_deities_and_you_ep_9.qmd
          - href: 1990/august/mccool_people_blanchard_the_hyperborean.qmd
        - section: September 1990
          contents: 
          - href: 1990/september/primeval_deities_and_you_ep_10.qmd
#Format
format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 0.75em
    #HTML themes: https://quarto.org/docs/output-formats/html-themes.html
    theme: 
      dark: [darkly, styles_dark.scss]
      light: [styles_light.scss]
    toc: true