---
title: "M^c^Cool People: Dr. Petra Pufferfish"
mainfont: Courier Prime
---

McCool FM - Interview Transcript <br>
Maggie M^c^Cool-Dr. Petra Pufferfish,  22nd April 1990, 11.00 a.m.

__Maggie M^c^Cool:__
Well, that was a bit disparaging wasn’t it? Anyway, it’s the 5th of April 1990, you’re listening to McCool FM and I’m your host Maggie McCool. Today we have a special guest, Dr. Petra Pufferfish. Previous head scientist of The Centre for Genomics and Cloning. Thanks for joining us today Petra.

__Dr. Petra Pufferfish:__ Hello, and please call me by my full name and title, Dr. Petra Pufferfish.

__MM:__ Oh, I am very sorry Dr. Petra Pufferfish.

__Dr. Petra Pufferfish:__
Apology accepted Mag.

__MM:__ Right, well let’s first address the rumors that you died in 1989 and why you have only resurfaced now.

__Dr. Petra Pufferfish:__
Greatly exaggerated rumor as you can tell. My ex-colleague Rang thought he saw me die and spread some distasteful rumors that I was just a head in a jar, fabrications. I’ve only re emerged now to introduce my new business venture called The Positive Pan Plan

__MM:__ Was that Dr. Ranga Doshi from the CGC?

__Dr. Petra Pufferfish:__
Yes Mag. That is Rang from the Centre for Genomics and Cloning. But back to what is important. As you know I am the Primeval Polytheist. I am the only human blessed by all four of the deities. I am the only person they can all agree on and so I am the number one Gaian in the world.

__MM:__ Yes, that is quite an amazing feat. Somehow getting Nyxmera and Tartarus to agree with something is a huge accomplishment.

__Dr. Petra Pufferfish:__
Thank you. So the Centre for Genomic Cloning was not enough for me. I am forming a new business and that business is the world. I already have Blanch and Sol on board as well as many others. They all believe in my eminence.

__MM:__ Yes, your initial funding is the highest of any venture capital ever. Congratulations. However, with the recent theft of the Koh-i-Noor from the British museum some are questioning human ownership. It was afterall stolen by a Talos, an aspect of tartarus. What do you make of this?

__Dr. Petra Pufferfish:__
We can of course own things from each other but if a deity wants something that belongs to them, they will have it.

[end of excerpt]
