---
title: "M^c^Cool People: Blanchard the Hyperborean"
mainfont: Courier Prime
---

McCool FM - Interview Transcript <br>
Maggie McCool-Blanchard the Hyperborean, 18th August 1990, 11.00 a.m.

__Maggie M^c^Cool:__
Before I get to the interview please let me say how proud I am of this radio station show and how far it has progressed in so little time. We have had such big names but none bigger than today’s. Welcome to McCool Blanchard the Hyperborean.

Blanchard the Hyperborean: It is a pleasure. I have really enjoyed the show. Such interesting guests I didn’t want people to miss out on me.

MM: I’m flattered, thank you. For those who don’t know of the many feats of Blanchard the Hyperborean please indulge me in listing them. He is an Austrian born american film star, polar and cryogenics researcher, governor of British Colombia in the USA, successful entrepreneur, multiple gold medal winter olympics winner and much more. How does a man in their 40s have so much energy and outcompete other athletes in their 30s?

BH: As hard as it is to believe I am in my 40s. But to answer your question I live a healthy and relaxing life in the cold. I love Vancouver with its cold and ice and snow. Its stillness lets me go with the flow at a leisurely pace. Though a leisurely pace for me is fast for others. 

MM: It does look like a lovely city in the winter though a bit nippy for me. We know you helped make Vancouver a big city for movies with some calling it the Hollywood of the North.

BH: Please I like to call Hollywood the dry Vancouver.

MM: I love it. If it is ok I wanted to briefly talk about your hometown in Austria. What was it like and do you regret what happened to it?

BH: My upbringing in Seefeld in Tirol was adequate. It was a small village but my friends and I did enjoy skiing on the nearby mountains. However, I outgrew it as did ERA, The European and Russian alliance. The super nation decided to abandon most inland settlements and focus the populations in existing and new port cities on the coasts. Practical but with all the different cultures combining together there was going to be problems with integrating everyone. A big reason they did this was to allow the war torn country to be reclaimed by nature, however deep hatred between different countries still existed. 

MM: How did they manage?

BH: Lots of tactics but the main one was to make the shared culture of ERA come from outside, specifically American culture. Some will say it made ERA too easily swayed by outside culture but it's what made me love American movies. I got my chance to enter the movies after making a splash in the 1980 winter olympics at Lake Placid in New York. From there everything just went my way.

MM: Speaking, it was horrible what happened to many of your fellow members of The Pharos club but congratulations on becoming its new leader.

BH: It was horrible, I had many friends there and was initially sad I could not make the get together due to the press tour of Blondie & Scaly-man-thing-guy versus the roaches from outer space. Of course now I’m relieved and hope to continue the club and finally find the home of Proteus, unfortunately its as elusive as ever. By the way, what did you think of my directorial debut of Blondie and Scaly-man-thing-guy? 

MM: Amazing! It really brought it back to its roots and I loved the action. I’m sad it's the last film of the franchise but so happy it ended in such a poignant, emotional, and bombastic manner.

BH: Great it sound like it would be suited for you and that Pat guy. I felt like you two would make a cute couple.

MM: Yes we do… anyway, you have so many projects going on. Is there any on the horizon we should be specifically keeping an eye out for?

BH: Yes, I have a big project I have been working on behind the scenes. It's well under way. I’m going to Hong Kong for the next step and the whole world will see the fruition of our plans before the end of the new year.

MM: Our plans? Are other important people working for you in this project?

BH: No, I’m working for an important genius for this project.

[END OF EXCERPT]

