---
title: "PAAR: HARM"
mainfont: Special Elite
---

MISSION <br> 
**H**ORSESHOE CRABS **A**TTACK **R**ANGA’S **M**ETHODS

**MISSION LOCATION** <br> 
LANTAU ISLAND AND CHEK LAP KOK, HONG KONG, SAE (SUPREME ASIAN EMPIRE)

**MISSION STARTED - MISSION CLOSED** <br> 
1434, 16 AUG 1990 - 1643, 20 AUG 1990

**CLIENT - CONTRACT DATE** <br> 
PUMICE CONSTRUCTION -  12 AUG 1990

**REMARKS** <br> 



**MERCENARIES INVOLVED - CODENAMES - STATUS** <br> 
████████████████████ - DAZZLING FIREWORKS - ACTIVE <br>
████████████████████ - LANCED BULL - KIA <br>
████████████████████ - STEAM GAZELLE - ACTIVE <br>
████████████████████ - BLINK HARE - ACTIVE <br>

https://m-gemmell.github.io/PRIMEVAL_DEITIES/Missions/M-HARM.html

Last session of PUML the team successfully killed the cruel creator of the Mutant Horseshoe crabs. This gave Farrier, the Brooding Horseshoe Crab, the revenge she so desired, allowing her to leave the island. Unfortunately Blanchard the Hyperborean took advantage of Farrier's exit to capture her. What is his intentions? Is it related to Dr. Petra Pufferfish? Find out in tonight's mission "Blanchard's Winter".

AT end Blanchard the Hyperborean steals Farrier. The team find her lair frozen over and her missing but don't know who did it.
Pat does some digging finding out that a shipment of ice got hauled from the port to Iceland (near titanic).
The dock workers think it strange that Iceland would need ice from Hong Kong.
Unfortunately the tanker went missing in the Bermuda triangle.
However, it was deliberately crashed by Blanchard's forces who got Farrier and transported it to the wreck of the titanic.