---
title: "M^c^Cool News: 04 Mar 1990"
mainfont: Courier Prime
---

__THE HEADLINES AT 1400 ON SUNDAY 4TH MARCH 1990__

Heyo it’s Maggie McCool. You’re listening to the 2pm McCool news on the 4th of March 1990.

I hope you are all keeping warm in this chilly spring.  In the news today we’ll cover:

A recent robbery at the University of Cambridge occurred recently. Witnesses say they saw an individual escaping the scene with a frozen head.

Citizens of the town of warboys are starting to repopulate their town after a horrendous DOT raider attack caused by the new year earthquake. Reconstruction has been swift due to Pumice construction.

The Royal Chambers Company are back on tour. An infamous company with unsavoury rumours surrounding them. Even so they are the best around and people are excited.

After the news we have a new M^c^Cool people. I’ll be interviewing leading CGC (Centre for Genomics and Cloning) scientist, Dr. Ranga Doshi. We’ll discuss the use of Horseshoe crabs in medical research.
