---
title: "PAAR: DELVE"
mainfont: Special Elite
---

MISSION <br> 
**D**OT **E**XPEDITION **L**EADS TO **V**EIN **E**NCOUNTERS

**MISSION LOCATION** <br> 
WARBOYS, CAMBRIDGESHIRE, ENGLAND, BIWAYS

**MISSION STARTED - MISSION CLOSED** <br> 
1429, 06 FEB 1990 - 1429, 06 MAR 1990

**CLIENT - CONTRACT DATE** <br> 
BIWAYS MILITARY -  05 FEB 1989

**REMARKS** <br> 

The Biways is a great place to have a mercenary company since we are safe from repercussions from other governments whilst here.
Unfortunately it means when the BIways government call I have to bark and clap like a happy seal.

Although coming out a month later our team spent less than a day of their time in the DOT. Could have been better but also could have been a lot worse.

**MERCENARIES INVOLVED - CODENAMES - STATUS** <br> 
████████████████████ - VEILED NIGHTJAR - KIA <br> 
████████████████████ - CRACKED BATFISH - ACTIVE <br>
████████████████████ - SIGHTLESS TRUFFLE - KIA <br>

VEILED NIGHTJAR killed by the obsidian blade of an Obsidian lava talos
Writeup: Session writeups
https://m-gemmell.github.io/PRIMEVAL_DEITIES/Missions/M-DELVE.html
Session 2 write up In DELVE our team of 3 mercenaries (Truffle, Nightjar, and Cracks) were ordered to converge on the town of Warboys, Cambridgeshire. They found it ransacked by DOT raiders, able to breach the surface due to an earthquake that had unveiled a cave system at the nearby extinct volcano.The team was tasked by the biways military with stopping any further raids by any means necessary. They entered the cave of Diorite, a magma based rock with a salt and pepper colour. Truffle decided to blindfold themself, allowing their sense of smell to lead the way. The rest of the team using the light of the ever present lava to guide theirs. They encountered living blobs of lithium which exploded in a chain reaction leading into a cave in. No choice but to go deeper the team encountered a sentient column of bismuth. With a heavy machine gun and warhammer it attacked only for Nightjar to steal its warhammer and smash it to pieces with a deadly somersault. Deeper they found the raider encampment, in a state due to the living rocks and lava. The Raider leader tried to parley but was swiftly dispatched by Truffle, hater of cheese eaters. The team was fighting hard and Cracks brought forth another pillar of lava, incinerating 2 raiders. However, this allowed a Talos made of lava and obsidian to emerge and strike down Nightjar, RIP. The team partnered with the raiders and took care of the Talos threat. Tremor, the raider’s magnetic slinger and Unicorn, a new PUML member, brought forth a peaceful resolution. It was time to kill the other Obsidian lava Taloes to stop them from reigniting the volcano and allow the raiders to go back into the DOT.
In the reservoir chamber the Taloes sacrificed some humans and began their ritual. Truffle and Tremor tried to sneak around only for Cracks’ bad luck to cause some lava to erupt onto Tremor who shouted in pain. Tremor was immediately skewered by one of the Taloes’ Obsidian spears. Cracks tried to help only for his new Panzerschreck to miss the Taloes and hit his team member Truffle, RIP. With his second team kill in the bag Cracks was attacked by a Talos. To confuse the entity he changed himself into a squirrel. Literally flying into the scene with a parachute, Steam gazelle helped take care of the rest. With Unicorn using a flare gun as a distraction Cracks performed an ultra successful RPG shot in squirrel form to kill the last Talos. The leftover raiders rushed past them giving the team a buggy to escape the now collapsing cave. They rushed out with good driving and a smoke grenade wielding squirrel to bypass more Taloes. Up next was a jump over a river of lava. Steamy tried to use their parachute to allow the car to fly over only for them to sail off by themselves. However, with quick thinking Unicorn drove over a ramp and Steamy launched themselves over the bridge and back into the buggy. With a slo-mo explosion of lava they escaped the tunnel and were rewarded by the military with a decommissioned base and helicopter.

Mention SIGHTLESS TRUFFLE seeing his younger self.
