---
title: "M^c^Cool News: 06 Jan 1990"
mainfont: Courier Prime
---

__THE HEADLINES AT 1400 ON SUNDAY 6TH JANUARY 1990__

Well doesn’t that sound grand. A Si señor opened locally to me, I’ll just have to find someone to go with.

Good afternoon, I’m Maggie McCool and you’re listening to McCool FM. We’re all slowly waking up from the new year and so there is not too much going on.

Saying that we had our first high profile wedding of the decade yesterday. River Dullcoin, daughter of Marian Dullcoin, and River Ox, olympic gold winning figure skater and coach, were married yesterday. The picture and coverage show a beautiful venue by the Ruby River with homages to Tartarus and Proteus. What I would have given to have been a fly on that wall.

The Biways and ERA, The European & Russian Alliance, are still in discussions for a new trade deal. We at the Biways, that is the British Isles, Greenland, Iceland, and other islands, have always benefited from being a small neutral nation separate from the five major superpowers. However, our government intends to leverage our abundance of nuclear power and research to get us a favourable deal. A deal with the global trade hub would be beneficial.

Repairs are still underway from the damages of the new year’s quake in Cambridgeshire.

{CONTINUE THIS}