---
title: "M^c^Cool People: Sol"
mainfont: Courier Prime
---

M^c^Cool FM - Interview Transcript <br>
Maggie M^c^Cool-Sol, 21st January 1990, 11.00 a.m.

__Maggie M^c^Cool:__
You’re listening to M^c^Cool FM and I’m your host Maggie M^c^Cool. 
Today we have a very special guest, Sol, the sole survivor of the Laser-US space station. 
A devout Sun of Nyxmera, they are now touring their new book “Sol the Ablated”. 
Welcome Sol.

__Sol:__ 
Happy to be here Maggie M^c^Cool.

__MM:__
Why the "Ablated" Sol?

__S:__
Ablation is the process by which parts of an object are removed by destruction.
As a meteoroid falls through to our planet it is destroyed layer by layer via friction with the atmosphere.
This is why meteorites can be cool when they first land, as the hot surface has vaporised.
When I fell down to earth from the station I became ablated.
All my physical features were worn away leaving  plain, like a mannequin.
Some would say I was reborn.
I say I was ablated.

__MM:__
I'm so sorry you went through that, it sounds incredibly traumatic.
Now Sol, we all know that Nyxmera called down the asteroid that killed the dinosaurs because it was bored. 
As a Sun of Nyxmera myself, I was wondering, why were you part of the Laser-US program?
Surely if Nyxmera sends an asteroids to destroy us we should abide by its will?

__S:__ 
I did it to entertain Nyxmera. 
If Nyxmera really wants us gone it can call down thousands of asteroids until one clears us off the face of the earth. 
Nyxmera could stop containing Tartarus and let it engulf us in lava. 
There are so many ways it could exterminate us. 
I don’t pretend to understand its intentions but I think it is safe to say we are entertaining Nyxmera through our struggles and pursuits. 
It is not done with us yet and we should be grateful.

__MM:__ 
Well you have me convinced! 
As you allude to, many like to personify the Primeval deities when they are anything but human.
Why do you follow Nyxmera when you come from the Gaian super nation of the USA?

__S:__
I have always liked to watch and study.
It is only natural I follow a deity that shares this trait.

__MM:__
I can empathise.
Next, I believe you are going to read an excerpt from your book: "Sol the Ablated".

__S:__ 
Yes, thank you. 
I will begin.

As the most interesting and exciting person I knew it was hard to find to those with a similar point of view.
The LASER-US incident alleviated my isolation in 2 ways.
I was ostracized from the USA, blamed for the station's demise.
Through this I escaped the drudgery of the nation.
Its inhabitants so thoroughly educated and removed of original thought.
Away from the fog of the states' unity I can see more clearly than ever.
That was the first change.

The second came in the new people and groups I met......

__SILENCE__

__MM:__
Sol... Sol.... Are you ok?

__S:__
Oh yes, sorry I got lost in thought.
Where was I?

__MM:__
The second came in

__S:__
the new people and groups I met.
There were still many I could barely see, like the light of dull far off stars.
But there was one who shone like Sirius, the brightest star in the night.
She shared her goals and showed me the power inside.
Now I can gift our vision and make the world a better place.

__MM:__
Wow, it seems you have some lofty goals.
Sorry if this is impolite but I must ask.
Due to the LASER-US incident you are now blind, amazing shades by the way, so how do you intend to carry on your work?

__S:__
Of course the sight-impaired have a lot of difficulty working with lasers.
Not being able to perceive light when working with it is a major difficulty.
Now I am part of a.... think tank.
We are very new so its only for the eyes of the members and investors currently.
Expect great things, our leader is a visionary.

__MM:__
I look forward to seeing more in the future.
If any members would like to be interviewed please let them know the invitation is open.

__S:__
Thank you.
I will.

__MM:__
Many people are wondering, how did the LASER-US station fall?

__S:__
I told them that the capacitors were not suitable for a larger scale ablation laser.
They rushed us because they wanted the technology for military purposes too.
Because I pushed back they demoted me and replaced me with an incompetent fool who was too stupid to say no.
They broke safety protocols and made me the figurative and literal fall guy.

[end of excerpt]
