---
title: "PAAR: AVOW"
mainfont: Special Elite
---

MISSION <br> **A**TTEMPTED ASSASSINATION OF THE **V**EILED AT THE **O**PULENT **W**EDDING

**MISSION LOCATION** <br> WEDDING VENUE AT █████████████████ ON THE RUBY RIVER, MONTANA, USA

**MISSION STARTED - MISSION CLOSED** <br> 1429, 04 JAN 1990 - 0245, 06 JAN 1990

**CLIENT - CONTRACT DATE** <br> ████████████████████████████ - 20 DEC 1989

**REMARKS** <br> 
We were offered both the protection detail and assassination jobs for this mission. 
Two members of the three person team voted for the protection gig. 
They aren’t necessarily fans of the client and their kind but they thought it would be awful if two brides died on their wedding day.

The following after action report was generated after debriefing the Mercenary VEILED NIGHTJAR on ███████████ at █████. 
FLUSTERED TURKEY flew the coop and the less time I spend with the wizard, CRACKED BATFISH, the better.

The team arrived at the wedding venue the day before the wedding. 
The ladies/birds (NIGHTJAR & TURKEY) were disguised as bridesmaids (one for each of the brides) whilst BATFISH infiltrated the venue as staff. 
Incognito, to not interrupt the special day, they aimed to discover and stop any assassination attempts of either or both of the brides.

THE KING <br> 
The first assassin to stop was ███████████, a Camera Obscura Shutterbug codenamed THE KING. 
She infiltrated as a silver adorned guest performing card tricks and gossiping. 
She is a well known celebrity and even amongst her ilk is known to be especially glittery. 

To start the investigation NIGHTJAR, ever the professional, discovered from her fellow bridesmaids that one of the wedding rings had gone missing.
Blending in with the crowds and gathering intel their prime culprit became ███████████ aka THE KING. 
TURKEY lured her away from the crowds into the brides’ matrimonial bedroom.
I say bedroom but it was in fact an entire house made of ice, supposedly fashioned off a hotel in Sweden. 
Whilst in the ice cabin TURKEY found the ring on THE KING’s wedding finger, covered by a specially designed silver ring.

TURKEY signalled to NIGHTJAR, hiding outside, to grab the ring with her teleporting yoink ability. 
As TURKEY kept THE KING busy, NIGHTJAR brought the ring to BATFISH who immediately recognised the Midas curse on it. 
With his advice they eliminated THE KING to remove said curse.

Turns out THE KING was Queen Hermodike II, the wife of King Midas, ungoldified in modern times. 
She was able to curse gold items with the midas touch by wearing them. 
After a certain amount of time the item would absorb enough of cursed energy from her to become a gold mine*. 
After she takes it off the next time it is adorned the wearer is goldified.

After the assassination-free ceremony everyone congregated outside. 
Wedding guests marvelled at an incredible figure skating performance⁂ and a new mysterious golden statue in its centre. It depicted a queen reaching out for the future with a hand missing its pinky finger. 
I’m sure they had fun theorising whose wedding gift it was.

THE ANTIDOTER <br> 
The second threat was █████████████████████, another Shutterbug codenamed THE ANTIDOTER. 
As we were previously offered the assassination job I knew the client wanted the brides killed either at the altar, during their first dance, or when they consummate their wedding. Very cruel but at least we knew our clients were safe during the dinner.

The team carried out a three prong attack. 
TURKEY tested all the food and found it all to be poisoned through its taste. Yet it seemed to have no effect. 
BATFISH, disguised as a waiter, found out that one of the cake team had died. 
They had found the body in a smoky freezer. So it was up to the team’s doctor, NIGHTJAR, to quickly figure out the cause of death. 
She discovered that he had died of an extremely deadly poison. However, he was the only victim thus far.

Thankfully one of the three core rules of Camera Obscura is “Do not kill, harm, or kidnap any civilians except the target during a mission unless the client allows it”⏺, they had not. 
With some good cop/bad cop by TURKEY and NIGHTJAR🛆 they narrowed in on the culprit, █████████████████████ aka THE ANTIDOTER. 
Hidden on his body they found a 2 part poison. Each part is harmless by itself but deadly when consumed within 4 hours of each other.
One part was in all the food except the cake and the other part was in the cake. The two birds were elated but too late they realised the wedding cake was gone.

What was meant to happen was that the brides would have eaten some cake and then left to quickly get changed for their first dance. 
They would come back and perform the death waltz. 
Thankfully, BATFISH figured there must be an antidote. During NIGHTJAR and TURKEY’s interrogations he was casting a ritual♢ in the fridge with the body. 
He determined the smoke, in the smoky freezer, had the antidote in it. 
THE ANTIDOTER had tried but failed to save his accidental victim.

Looking at the event timetable BATFISH found the smoke machine’s activation time had been changed. 
Instead of it activating as the brides returned for their first dance it was now set to activate just after they left to change. 
To prevent any issues he set it off as the brides were cutting into their cake. 
They looked furious at the shoddy time keeping but when one of them recognised BATFISH at the smoke machine she claimed she’d ordered it as a fun surprise so they all laughed it off.

The team captured THE ANTIDOTER and I recruited him.
He accepted.
He knew Camera Obscura would be unhappy with him due to the failure and the accidental death of a civilian.
He's a great chef on top of a great poisoner and even better antidoter.

The first dance was very moving with a live performance by Gaia’s wreath.
Of course being a super fancy party means they also got live performances of rock & metal bands such as Big Bismuth, Erupted Scars, and Hupselosα.

THE SILHOUETTE <br>
The third threat was a lot more direct.
After most of the guests had left the brides retreated to their matrimonial ice cabin in the back of the compound.
The stillness of the night was interrupted by bangs from the front gate.
THe normal security went to intercept but my team stayed to protect our ice queens.

Four combatants emerged over the back walls, climbing down from branch suspending ropes.
They were quick and tactical but my team was prepared.
With FAMAS F1s the assassins opened fire on my intercepting team.
One assassin's rope broke, his helmet fell off, a massive rock met his head, and he was accidentally shot by one of his team mates.
One down from BATFISH's bad luck.

The remaining three rushed to the building, seemingly not caring for their lives, just the mission.
NIGHTJAR intercepted one, both dipping and diving between various boulders in a well placed rock garden.
Bullets on rocks, boots on pebbles, and hot breath into the winter air.
The assassin couldn't get a bead until he could.
Light shone off his visor as he looked up at the boulder perched NIGHTJAR.
He shot but his trigger finger only felt air.
Confused he watched his trigger drop out of NIGHTJAR's left hand as her right hand pulled her own.
She'd intentionally lured him into a lit location to yoink his trigger.
Second down.

On top of rifle shots the periodic destructive boom of TURKEY's shotgun could be heard.
After a final shot she screamed about going into the forest to find the source but warned the fourth was heading to the cabin.
BATFISH and NIGHTJAR tried to catch up with the last assassin but he was too far ahead.
NIGHTJAR couldn't use her yoink ability so quickly again and even if she could it was deathly dark.
Continue the chase or try to shoot a fast moving target in with her pistol?
NIGHTJAR decided to run.
BATFISH slipped in his slippers.
TURKEY disappeared.

With a burst of mystical adrenaline NIGHTJAR suddenly sped up.
She heard an energising chant from behind, but with no breath for thanks she flew on.

The assassin reached the house.
He rammed through the door, shattering it like.... well like ice.
He zigged and zagged down hallways following the sound of the rock music the brides so enjoyed.
As he barged in ready to fire he hesitated, seeing three women rather than two.
In his momentary trance NIGHTJAR shot him from below the chin, bullet stopped by the inside of his helmet.
The brides, unfazed, let out an excited yell as NIGHTJAR fell into a figurative steaming heap.

But how had NIGHTJAR got to the room first?
She'd sneaked in through a secret escape hatch she'd found during THE KING capture and elimination, much faster than the twisting corridors.
It pays to be prepared and know your surroundings.

After the combat the bodies of the assassins were found.
They seemed to be normal citizens from the surrounding area.
By all intents they were average people, no crimes, average grades in school.
The only thing that linked them was that they were all so average.

At least that's the official report I got.
Thankfully we were able to get NIGHTJAR to help in the autopsies.
All was average except their eyes.
They all had the eyes of Nyxmera.
Each of them had a right eye of blue scleraβ with a yellow iris, like the sun on a blue sky.
On the other eye they each had black sclera with an iris of grey and purple, like the two moons in the night sky.
Literal eyes of Nyxmera.

Whoever lead the last set of assassins is not a shutterbug.
I have no other information about them, though someone must know something otherwise they would not have redacted that part in the official autopsy report I got.
They probably paid Camera Obscura for the first 2 attempts and tried to finish the job when THE KING and THE ANTIDOTER failed.
What I do know from NIGHTJAR is that the eyes of the 4 assassins were all identical pairs.
They were all exactly the same shape, size, and most importantly exactly the same iris patterns.
Not much to go on, I'll have to keep... an eye out.

CLOSING REMARKS

A successful mission with our clients going to lead a happy life together.
Considering the danger involved my team of three did very well.
Unfortunately TURKEY hasn't been seen again since she went went to investigate the source of these eyes.
She may have been recruited by Camera Obscura or the unknown other party. 
She voted to take the assassination job rather than the prevention mission so maybe she didn't like taking a protection gig. 
It’s a weird thought that a turkey would want to live in the USA.

**MERCENARIES INVOLVED - CODENAMES - STATUS** <br> 
████████████████████ - VEILED NIGHTJAR - ACTIVE <br> 
████████████████████ - FLUSTERED TURKEY - MIA <br> 
████████████████████ - CRACKED BATFISH - ACTIVE

*As in the explosive kind of mine, it's a pun <br> 
⁂Blanchard the Hyperborean was part of the figure skating performance. I love his action movies especially the Copper Cog Warrior series <br> 
⏺The other two are “Do not kill, harm, or kidnap any other Camera Obscura shutterbugs” and “Non-shutterbug mercenaries, bodyguards, and vigilantes can be eliminated with discretion” <br> 
♢They say this but I think it was more bad cop/worse cop <br> 
🛆More predictable than his spells but take longer apparently <br>
αLucky buggers <br>
βNightjar told me to use the proper names but for people like me: sclera is the white of the eys, iris is the coloured part, and pupil is the black part<br>