---
title: "The Primeval Deities and you: ep2 Nyxmera"
mainfont: Courier Prime
---

Hello listener and welcome to the second episode of The Primeval Deities and you. I am Dr. Harmon Atriti, Professor of Primeval studies at The University of Cambridge, and your vigilant host. In this series we are exploring the four Primeval deities and their influence on our world. In this episode we will investigate Nyxmera, the deity of the skies.

Who is Nyxmera? <br>
Nyxmera is the light. All the celestial bodies are known as the eyes of Nyxmera, the sun, the grey moon, the purple moon, and the stars. 
With these Nyxmera watches, it wants to be intrigued. Something its followers, Suns of Nyxmera, are more than happy to facilitate. <br>
Nyxmera is everything but rock, water, and life. 
It craves what it can’t take. 
There is so much of interest on our tiny orb of dirt, so Nyxmera is stuck in a perpetual gaze on our planet.<br>

What is the icon of Nyxmera?<br>
Nyxmera's symbol is a circle split in two.
On the left is a blue background with a yellow circle, the sun and the day sky.
On the right is a black background with one grey and one smaller purple circle, the moons and the night sky.
This symbolises Nyxmera's eyes but also its duality.
It loves and demands extremes; good and evil, comedy and drama, love and war.
It is like a king and we its jesters.

What are the tenants of Nyxmera?<br>
Four deities, each with four tenants.
Nyxmera's are: <br>
Observe and sow intrigue. <br>
Balance via duality. <br>
Manipulate and use others. <br>
Eternal beauty over transience.<br>

Who follows Nyxmera?<br>
The admirer's of Nyxmera are called Suns of Nyxmera. 
They are the entertainers and the entertained.
The artists and the aristocrats.
They are those who create beauty and those who are bestowed beauty. <br>
Though we humans primarily consider entertainment as arts and sports, to Nyxmera this also includes science.
Suns of Nyxmera take an interest in physics, especially related to space.
After all, what is Nyxmera but the duality of particles and waves, that is to say light.<br>
One of the most exciting periods of the current primeval era was the space age.
The USA, ERA, and SAE started the race to reach the grey moon.
But once the Japanese refugees claimed their desire to make it their home the whole world banded together to grant their wish.<br>
Now we have two nations that follow Nyxmera, the SAE, Supreme Asian Empire, and the Moon.
The SAE is the largest nation by population, a blessing and a curse.
It is led by China and India, two countries who never agree but always compromise.
Despite this they are now the quickest growing super power set to dethrone the USA.
Some say this bickering and progress is caused by the variety of cultures across and even within the many countries.
Either way I do enjoy good martial arts and Bollywood films.<br>
On the other side not much is known about the Moon, the distance allowing them to easily isolate.
We know they live in 2 major cities, Kaguya and Usagi, and that they specialise in combustion light-gas guns, hydrogen batteries, and mecha.
With these three technologies they plan to retake Japan from the Kaiju.
We will learn more about these and other nations in future episodes.<br>

How is Nyxmera's presence felt? <br>
As with all the deities Nyxmera's will shapes our existence for its own pleasure.
It pushed Tartarus deep into the earth, transforming the surface from inhospitable lava to rock.
This allowed Proteus and then Gaia to take hold and so provide Nyxmera the variety it craves.
Of course Nyxmera can tire and grow bored with the machinations of life. <br>
And so as we transition to our next topic as Nyxmera can transition the status quo of Earth.
It carries out these resets with immense violence through asteroids and meteorites.
The destruction of Hitler's bunker.
The extinction of the dinosaurs.
The creation of our moons.
These impacts and many more were caused by brought down by Nyxmera.
Meteorites and their craters are the relics and shrines for the Suns of Nyxmera. <br>

What are the avatars of Nyxemra? <br>
Though there are many other ways we feel its presence the most obvious and perhaps strangest is through its Starvatars.
A crude portmanteau of star and avatar they are the light of a star given physical form.
When a Starvatar exists the light of its star can no longer be seen in the night sky.
Instead the light now exists as a hard light entity, taking the name of its star or constellation. <br>
Starvatars are humanoid like beings made of the night sky. 
Their bodies are pitch black with twinkling lights. 
They have limbs that taper down to points like the human depiction of a star on paper. 
Invisible digits allow them to handle anything a human could. <br>
All Starvatars of Nyxmera look nearly identical except for their heads. 
Many of these are animal heads such as a Lion, Bull, or Scorpion for the Leo, Taurus, and Scorpio constellations.
Other stranger examples include a Leg, an Arrow, and a seven pointed star for the Andromeda/Kui and Indus constellations, and the Peiades star cluster.
On each of their heads is one bright light, their star’s light.
This is their eye and with it Nyxmera watches too.

That is a quick introduction to Nyxmera and its infinity of eyes.
I am eternally grateful for you lending your ears.
Though we covered much on Nyxmera there is always so much more to discover.
On the next episode we will chew on the existence of the furious and justified Tartarus.
I look forward to speaking with your then dear listener.
