---
title: "PuMP: VEILED NIGHTJAR"
mainfont: Special Elite
---

__BACKGROUND__ <br>
A medical doctor whose mentor was Dr. Moira Finn. They were both known to go above and beyond for their patients. Eventually Dr. Finn died of a heart attack, stroke, and infection caused by a bad tooth she should have seen the dentist about. NIGHTJAR was present and tried but failed to save her. Dr. Finn’s other mentees used this as an opportunity to put the blame on NIGHTJAR. Subsequently, she lost her medical license due to "misconduct". Not able to help others through medicine, she decided to do so as a mercenary with PUML.

__PHYSICAL FEATURES__ <br>
__Monochrome medic:__ She’s the dictionary definition of a goth doctor. Short perfectly manicured black nails and a black band t-shirt of "Not our dames". Her smoky eye makeup is impeccable. Yet it could never be dark enough to cover her periorbital hyperpigmentation*.

__PERSONALITY QUIRKS__ <br>
__Adaptable but disconnected:__ Due to her experience as a doctor in ER she can lead a team, create a plan, and quickly pivot when the circumstances change. Unfortunately she also speaks like a doctor, frequently confusing enemies and team mates alike. <br>
__Meticulous yet blunt:__ If given time she likes to prepare with an extreme level of methodical research and planning. However, when she’s in the action she loves to start blasting and smashing.

__FAVOURED GEAR__

- Medical kit
- Baseball bat
- Walther P88 semiautomatic pistol

__PRIMAL STATS__ <br>
JAWS:0 | EYES:0 | LIMBS:+2 | NERVES:+1

__PRIMAL ABILITIES__ <br>
__Yoink:__ She can teleport items into her hands. The three stipulations are:

- The item must fit on her palm
- She must be able to directly see or touch the item⁂
- This skill has a refractory period of a few minutes

__Perfect landing:__ She can seemingly land on her feet, with no injury, from any height. With this skill and her general acrobatics she is a master at traversing over and around obstacles.

\*Dark circles under the eyes generally caused by fatigue <br>
⁂Having a concealed weapon that she can directly teleport into her hand is handy
