---
title: "M^c^Cool News: 7th Dec 1990"
mainfont: Courier Prime
---

__BREAKING NEWS AT 1517 ON MONDAY 7TH DECEMBER 1990__

__MAGGIE M^C^COOL__
It's Maggie McCool and this is McCool FM. This is a special report. A mouth to the DOT has opened in the White House lawn. Out emerged Taloes led by one with the Kohinor on its head, the british crown jewel. One such as it had never been seen. A combination of lava, obsidian, and radiation. If that wasn’t strange enough, Dr. Petra Pufferfish then emerged from the mouth, seemingly being escorted by the Taloes who left her as they descended once more, sealing the hole behind them. She commandeered the presidential address to give the following message.

__DR. PETRA PUFFERFISH:__
Hello my world. I am Dr. Petra Pufferfish. Lead designer of the Perfect Pan Plan. Our first step to taking control of the world is to conquer the United States of America. Nothing personal it is just you are the most powerful nation but we will succeed. For the first step Blanch* will use his Far⁂ Powered Climate Manipulator to freeze the United States of America in Blizzards. To prevent this you must pay us 100 million dollars every day.  Don’t worry we have so many more plans, it will take a titanic effort to stop us. That is all I need to say.

__MAGGIE M^C^COOL__
After her statement the guards went to apprehend her but a subsequent explosion left no sign of her or her would be capturers.


*Blanchard the Hyperborean
⁂Farrier the Brooding Horseshoe crab mutant