---
title: "The Primeval Deities and you: ep8 Primality"
mainfont: Courier Prime
---

Hello listener and welcome to the eighth episode of The Primeval Deities and you. I am Dr. Harmon Atriti, lecturer of Primeval studies at The University of Cambridge, and your eager host. 

Recently the term Primal humans has gained widespread adoption around the world. This refers to humans who have been gifted special powers from one of the Primeval Deities.

However, it is not just humans who can have these powers. All entities, all objects, and even forces can be bestowed with these traits. In academic circles we call this effect divinity or primevality. But I now choose to introduce the term Primality. I hope you will help in the worldwide adoption of this new term.

But what is primality? We deem something to be primal or have primality if we can not explain a phenomena with science. These can be as boring as rocks rolling up a specific hill to more dangerous affairs such as the Kaiju of Japan. However they can also be helpful. There are areas where wind always blows, making perfect locations for wind farms. Ultimately the primality of forces and weather are very much up to debate. It can be hard to determine what is a natural or primal phenomena when we do not fully understand either. However, it is my theory that our world is so intrinsically entangled with the Primeval deities that once folklore could be explained with science now science can be explained by the Primeval deities. If only we could directly communicate to them.

This brings us onto Primal humans. You may be wondering how we know so much about The Primeval deities when we can’t communicate with them. Much of what we know is inferred but some have spoken with them. Primal humans have a connection to a deity allowing limited communication.THrough this they have been assigned personalities that we can understand. Of course this is but the surface. Primal humans will have powers. A Dotter may have such string teeth they can east metal. A Gaian may be able to control the microbes in their body. A Protean may grow gills. A Sun may even be able to see the future. These sound crazy but are indeed real life examples.
