---
title: "Commercial: Gaia's wreath"
mainfont: Courier Prime
---

1989 McCool FM - :60 second spot

---

__ANNCR:__ The six members of Gaia’s wreath have been hard at work and are now ready to release their fourth studio album: Harmonies through discord. 

__MUSIC: (BRIDGE) WHEN SCISSORS UNITE PAPER DIVIDES__

__ANNCR:__ They are eminent fusion folk band of the Biways. They and their music representing its countries.

__ANNCR:__ The refined English Rose on fiddle and sombre Welsh Cennin Pedr on flutes.

__MUSIC: (BRIDGE) COMFORTABLE STAGNATION__

__ANNCR:__ The lively Irish Seamair on harp and cacophonic Scottish Cluaran on accordion. 

__MUSIC: (BRIDGE) APATHY MASKS ENVY__

__ANNCR:__ And of course the mesmerising Icelandic Holtasóley on vocals and the Greenlander Niviarsiaq on drums.

__MUSIC: (BRIDGE) SEA OF LIMBS__

__ANNCR:__ Experience the culmination of the greatest folk band the world has ever seen. Buy Harmonies through discord at all good record stores today.

__MUSIC: (FADE) HARMONIES THROUGH DISCORD__
