---
title: "M^c^Cool FM 14:00 News Script"
mainfont: Courier Prime
---

THE HEADLINES AT 1400 ON SUNDAY 31ST DECEMBER 1989

Good afternoon everyone, It’s Maggie M^c^Cool. It's the 31st of December 1989 and this is the first ever 2pm M^c^Cool news.

Happy new year and welcome to M^c^Cool FM. I hope you are looking forward to the new decade and its promises. I also hope you’re prepared for the inevitable chaos and madness that this world regularly gifts us.

But first let's think back to the past. Many remembrance services are being taken worldwide to remember all those lost to the horrors of world war 2. The brave soldiers, the concentration camp victims, all those taken by the kaiju infestation of Japan, and many many more. 

From the scorched and cracked earth peace took root and hasn’t let go. The super nations have maintained the nuclear arms ban and only minor skirmishes have occurred since 1945. We wish the Mooners luck in their future plans of reclaiming their homeland of Japan.

In this special report we’ll cover the major news highlights of this waning decade. Including:

The first artificial cloning of a mammal by Dr. Petra Pufferfish of the CGC. This was followed by her disappearance with Dr. Rangi Doshi, previous COO, taking her place as CEO. 

The rise of the illicit drug “Holy water”. Its rapid spread throughout the world is unprecedented and many think related to the powers of Proteus.

The very recent destruction of Laser-US, a space station designed to save us from apocalyptic asteroids. The only survivor was Sol the ablated. The other asteroid deflection space stations are still under construction including the Las-ERA, Laser-CAC, La-Sae, and Laser-Oceania.

In a first scoop for M^c^Cool FM we’ll also talk about the earthquake we just felt in our Cambridgeshire studio. It was quite fierce!