---
title: "News story: M^c^Cool FM announcement"
mainfont: Newsreader
---

__A M^c^Cool new radio station signals a new decade__

by Kirtsy Sherman

It's the final month of 1989 and The Biways is getting a new radio station: M^c^Cool FM.

M^c^Cool FM will run a cornucopia of shows. 
From ordinary affairs such as the news and dramas to more eclectic shows. 
These include an interview show called “M^c^Cool People” and an educational show about the Primeval Deities called “The Primeval Deities and you”. 
Between all that excitement they’ll run popular, folk, and popular folk music.

The Ambitious radio channel will make its home atop the water tower on Rivey hill overlooking Linton. The Art Deco tower, built in 1935 to 36,  is now modified with a high powered radio able to broadcast to the entire Biways and beyond.

We talked to Maggie McCool, the founder and primary host of M^c^Cool FM, on her ambitions. She said:

“M^c^Cool FM’s going to be a household name! At least that’s what I need to tell myself. It would be mad to do all I’ve done if it wasn’t my goal. With the station I want to let everyone know what is going on in our great and interesting world. Some will accuse me of controlling a narrative with my biases. What's wrong with that? I need to let my personality inform the channel or else it’ll be bland radio channel number 8. I hope everyone will enjoy listening. Selfishly I’m eager to meet a variety of people with my interview show M^c^Cool people. It’s nice to think I’ll be a bit like Nyxmera, watching over the world from up high.”

Will listeners tune into M^c^Cool FM? Or will it merge into the fuzz of background radiation?

Maybe their recently announced intro for Maggie will give us an idea:

“M^c^Cool in name, M^c^Cool in nature, it's your host Maggie M^c^Cool on M^c^Cool FM!”