---
title: "PAAR*: GREEN"
mainfont: Special Elite
---

MISSION <br>
**G**REENLAND **R**ESEARCHERS **E**SCAPE WHILST WE **E**SCORT **N**OGGIN 

**MISSION LOCATION** <br> 
█████████████████████████████, GREENLAND, BIWAYS

**MISSION STARTED - MISSION CLOSED** <br> 
1652, 19TH DEC 1989 - 0452, 20TH DEC 1989

**CLIENT - CONTRACT DATE** <br> 
UNIVERSITY OF CAMBRIDGE- 18TH DEC 1989

**REMARKS** <br> 
The last mission of the 80s.
With it the 90s is fast approaching, wielding a nailed hurley.
My hopes of the new decade being stable and normal have been shattered like a knee struck with said hurley.

A simple but tough job this one.
We were to transport an object called the HEAD⁂ from a top secret Greenland research station to Nuuk, the capital city.
The station had been attacked multiple times by an unknown force.
The Greenland military tried to deal with it but constant blizzards around the base prevented any large scale deployment.
The researchers were to be airlifted to safety.
Our team would transport the HEAD over snow and ice during a break in the winter blizzards.

For the mission I chose SIGHTLESS TRUFFLE to lead.
His team consisted of the mad mage CRACKEd BATFISH, the reckless racer SUBSONIC HYDRA, and the colourful FLASHBANG FIDDLER.
A hard team to manage but if anyone can do it its TRUFFLE.

The following after action report was created from the debriefs of the uneaten members of the team.
It may seem preposterous, and if it was just from CRACKED BATFISH's recount I'd agree, but the whole teams' debriefs match.
Get ready.

ARRIVAL AND CONTACT<br>
The weather was calm all the way to the research base where the shenanigans started.
Each of my team was given a HEAD and told they had the real one.
They did tell TRUFFLE that he actually had the real one and the others had been lied to.
As the mission leader he played along seeing the logic and not wanting to demoralise the team.
The HEAD was far more valuable than Cambridge told me◉.
With their snowmobiles the team set off to Nuuk as the researchers evacuated in a few chinooks.

With a massive crack ringing through the air as the research base self destructed my team headed to Nuuk.
Only after an hour or so of traversal the blizzard once again arrived, like an unwanted grenade landing in your dugout.
Though difficult TRUFFLE was able to detect the scent of fur, sweat, and steel. 
Normally it would be impossible for an enemy force to track my team through a blizzard but they also had the power of smell on their side.
That's because they were fecking cyborg polar bears!
Not only that but they had side-mounted heavy machine guns and riders atop them.
These riders wore head encompassing helmets attached to the cybertonics of the bears and were equipped with stun sticks and Boyes anti-tank rifles.

The team attempted to outrun the two cyborg polar bears.
But they were faster and gained distance on my team.
With gunfire range fast approaching upon them SUBSONIC did something smart in theory but dumb in reality.
With the "real" HEAD in his possession he used his Kinetic transfer ability to increase the speed of his snowmobile and race far ahead.
He was too fast for both of TRUFFLE's warnings.
First, he didn't have the real HEAD.
Second, laying in wait ahead were two more cyborg polar bears.

SURF AND TURF<br>
At greater than 200mph SUBSONIC crashed into one of the hidden bears.
The impact killed it and flung SUBSONIC and the bear's rider off their vehicles♢.
This transitioned the chase to mounted combat.

As the other previously hidden cyborg rose up TRUFFLE lined up the sights of his Ishapore with the mounted rider's helmet.
Two shots cracked open his helmet, the third his skull.
The loss of its rider transformed the Polar bear from a composed steed into a wild animal.
It bore down on SUBSONIC and the unmounted rider.
Panicking, the once-rider seized his boyes rifle.
He shot, missed, and yelled in pain as the recoil broke his shoulder.
His screams turned into a squeal and then into silence as the bear started his meal with neck of ursestrianΔ.
TRUFFLE ploughed through the snow as fast as he could.
As the starved beast dined, SUBSONIC tried to sneak away.
But alas a massive metal boot does not make for a stealthy getaway.
One step with it into the snow gave off a large crunch, alerting the bear.
The second hurried step sunk deep, trapping SUBSONIC and sealing his fate as not so fast food.
With nothing to be done TRUFFLE turned to regroup with the others.

LIGHTS AND ROUNDABOUTS<br>
When SUBSONIC was rushing off the other two, BATFISH and FLASHBANG, attempted to deal with the initial cyborg polar bears.
They tried to distract the bears with suppression and evasion.
They succeeded in getting their attention but it also allowed the bears to get into firing range.
HMG bullets hit FLASHBANG's back-mounted shield like hail on a corrugated roof.
I'm sure the rider's anti-tank rifles would have ripped straight through my teams' armour.
Thankfully, it seems ursestrians can only concentrate on controlling their mounts and nothing else.

Not being able to outrun the bears FLASHBANG and BATFISH decided to circle and harass them.
They wasted the bear's HMG ammo but the sorcerer's ride took some hits.
It was now like its drivers namesake, CRACKED.
The two tried to take down their enemies but their firearms were next to useless against the foe's heavy armour.
A gridlock of bears and snowmobiles.

To get the part started again FLASHBANG dazzled one bear with a stun grenade.
The always insane BATFISH jumped onto its back.
Yanking the Boyes rifle from the rider he blasted through through him and the head of the bear^α^.
With the force of the gun and sudden stopping of the bear BATFISH flew off landing in a conveniently placed pile of snow.
Of course there was the other active cyborg bear who wasn't going to waste the opportunity to kill a crazy conjurer.
First TRUFFLe now it was FLASHBANG's turn to play hero.

BATFISH got up and watched a snowmobile and a cyborg polar bear racing each other to reach him.
He paused.
Though he's seen a bunch of wild shit^β^, massive bears are a primal fear for everyone.
Just as the polar bear reached BATFISH so did FLASHBANG.
With both his arms FLASHBANG saved the wizard.
His right pulled him onto the snowmobile.
His left blocked a ferocious bite aimed at BATFISH's head.
If it had been a normal arm the bear would have torn FLASHBANG straight off his vehicle.
Instead his hematite arm shattered under the jaws.
With mouth full of blood and crushed crystal the bear roared and FLASHBANG, with BATFISH in tow, fled towards TRUFFLE.

OFF WITH THE LEFT FOOT<br>
Regrouped with 3 mercenaries and 2 snowmobiles the team still had the HEAD to transport.
The blizzard was dying down, one Cyborg polar bear and rider was chasing them, one wild bear was ahead, and they could hear the sound of incoming vehicles.
With little time TRUFFLE charged towards the wild bear and his meal, FLASHBANG and BATFISH following.
Busy eating its meal the bear reacted slowly and my team narrowly passed it by.
Why endanger themselves?
Well the smart bastard TRUFFLE decided to play hero one more time and he grabbed SUBSONIC's big metal boot.
As they continued they heard the roars of 2 angry polar bears followed by the booms of an anti-tank rifle.
Losing their tail they eventually made it to NUUK and handed off the HEAD.

Though superfluous the team told me they sat together by the airport.
With a few beers they watched the LAS-USA burn up on reentry into the atmosphere backlight by a magnificent aurora borealis.
TRUFFLE stuck SUBSONIC's foot into FLASHBANG's empty HEAD device along side a few very nice whiskeys.

What was in the HEAD device?
Of course we weren't supposed to look and I'll definitely punish TRUFFLE for his snooping.
He told me it was a head^γ^.
It was very frozen so he couldn't ID it but I have my theories.

CLOSING REMARKS <br>
Overall a successful mission with only one member wounded in action (WIA).
It'll take a few months but we'll be able to regrow a SUBSONIC HYDRA from his left foot.
It would have been great to have recovered SUBSONIC's head and we could have two of him.
You know what they say, when Gaia gives you a foot make toe jam.

**MERCENARIES INVOLVED - CODENAMES - STATUS** <br>
████████████████████ - SIGHTLESS TRUFFLE - ACTIVE <br>
████████████████████ - SUBSONIC HYDRA - WIA <br>
████████████████████ - FLASHBANG FIDDLER - ACTIVE <br>
████████████████████ - CRACKED BATFISH - ACTIVE <br>

\*PAAR is the acronym for PUML After Action Report <br> 
⁂Highly Expensive Ambulatory Device<br>
◉I could have charged them more<br>
♢Do Cyborg Polar Bears counts as vehicles or mounts?<br>
ΔUrsus is the bear genus therefore bear riders would obviously be called Ursestrians (like equestrians)<br>
αPretty awesome I must admit<br>
βSo he claims anyway<br>
γShocker I know

