---
title: "PAAR*: AVOW"
mainfont: Special Elite
---

MISSION CODENAME <br>
__A__TTEMPTED ASSASSINATION OF THE __V__EILED AT THE __O__PULENT __W__EDDING

__MISSION LOCATION__ <br>
WEDDING VENUE AT ________________ ON THE RUBY RIVER, MONTANA, USA

__MISSION STARTED - MISSION CLOSED__ <br>
1429, 04 JAN 1990 - 0245, 06 JAN 1990

__CLIENT - CONTRACT DATE__ <br>
________________________________ - 20 DEC 1989

__REMARKS__ <br>
We were offered both the protection detail and assassination jobs for this mission. Two members of the three person team voted for the protection gig. They aren’t necessarily fans of the client and their kind but they thought it would be awful if two brides died on their wedding day.

The following after action report was generated after debriefing the Mercenary VEILED NIGHTJAR on ____________ at _ _____________. FLUSTERED TURKEY flew the coop and the less time I spend with the wizard, CRACKED BATFISH, the better. 

The team arrived at the wedding venue the day before the wedding. The ladies/birds (NIGHTJAR & TURKEY) were disguised as bridesmaids (one for each of the brides) whilst BATFISH infiltrated the venue as staff. Incognito, to not interrupt the special day, they aimed to discover and stop any assassination attempts of either or both of the brides.

THE KING <br>
The first assassin to stop was ____________, a Camera Obscura Shutterbug codenamed THE KING. She infiltrated as a silver adorned guest performing card tricks and gossiping. She is a well known celebrity and even amongst her ilk is known to be especially glittery. NIGHTJAR, ever the professional, discovered from her fellow bridesmaids that one of the wedding rings had gone missing.

Blending in with the crowds and gathering intel their prime culprit became ____________ aka THE KING. TURKEY lured her away from the crowds into the brides’ matrimonial bedroom. She found the ring on THE KING’s wedding finger, covered by a specially designed silver ring. 

TURKEY signalled to NIGHTJAR, hiding outside, to grab the ring with her teleporting yoink ability. As TURKEY kept THE KING busy, NIGHTJAR brought the ring to BATFISH who immediately recognised the Midas curse on it. With his advice they eliminated THE KING to remove said curse.

Turns out THE KING was Queen Hermodike II, the wife of King Midas, ungoldified in modern times. She was able to curse gold items with the midas touch by wearing them. After a certain amount of time the item would absorb enough of her cursed energy in her to become a gold mine\*\*. After she takes it off the next time it is adorned the wearer is goldified. 

After the assassination-free ceremony everyone congregated outside. Wedding guests marvelled at an incredible figure skating performance\*\*\* and a new mysterious golden statue in its centre. It depicted a queen reaching out for the future with a hand missing its pinky finger. I’m sure they had fun theorising whose wedding gift it was.

THE ANTIDOTER <br>
The second threat was ____________, another Shutterbug codenamed THE ANTIDOTER. As we were previously offered the assassination job I knew the client wanted the brides killed either at the altar, during their first dance, or when they consummate their wedding. Very cruel but at least we knew our clients were safe during the dinner. 

The team carried out a three prong attack. TURKEY tested all the food and found it all to be poisoned through its taste. Yet it seemed to have no effect. BATFISH, disguised as a waiter, found out that one of the cake team had died. They had found the body in a smoky freezer. So it was up to the team’s doctor, NIGHTJAR, to quickly figure out the cause of death. She discovered that he had died of an extremely deadly poison. However, he was the only victim thus far.

Thankfully one of the three core rules of the Shutterbugs is “Do not kill, harm, or kidnap any civilians except the target during a mission unless the client allows it”\*\*\*\*, they had not. With some good cop/bad cop by TURKEY and NIGHTJAR\*\*\*\*\* they narrowed in on the culprit, ____________  aka THE ANTIDOTER. Hidden on his body they found a 2 part poison. Each part is harmless by itself but deadly when consumed within 4 hours of each other. One part was in all the food except the cake and the other part was in the cake. The two birds were elated but too late they realised the wedding cake was gone.

What was meant to happen was that the brides would have eaten some cake and then left to quickly get changed for their first dance. They would come back and perform the death waltz. Thankfully, BATFISH figured there must be an antidote. During NIGHTJAR’s and TURKEY’s interrogations he was casting a ritual\*\*\*\*\*\* in the fridge with the body. With it he determined the smoke had the antidote in it. Seems THE ANTIDOTER had tried but failed to save his accidental victim. 

Looking at the event timetable BATFISH found the smoke machine’ activation time had been changed. Instead of it activating as the brides returned for their first dance it was now set to activate just after they left to change. To prevent any issues he set it off as the brides were cutting into their cake. They looked furious at the shoddy time keeping but when one of them recognised BATFISH at the smoke machine she claimed she’d ordered it as a fun surprise so they all laughed it off.

The first dance was very moving with a live performance by Gaia’s wreath. I’m more a fan of prog rock but I wouldn’t say no to a private performance of theirs.

THE SILLHOUETTE <br>
After the wedding dinner entertainment and dancing took place. Our team got to enjoy the music of various famous rock & metal bands such as Big Bismuth, Erupted Scars, and Hupselos. No assasination attempts took place.
The third threat occurred after most of the guests had left and the brides had retreated to their matrimonial bed. Four heavily geared and skilled assailants armed with FAMAS F1s attempted to infiltrate the compound grounds. Our team narrowly stopped the assassination attempt with one assailant making it to the brides before being shot down. The brides were unfazed and found it quite exciting. Each assailant disappeared out of existence when shot, leaving behind their gear but no body. TURKEY went to investigate the source of these shadows but never returned. She may have been recruited by Camera Obscura. She voted to take the assassination job rather than the prevention mission. It’s a weird thought that a turkey would want to live in the USA.

[SAY with some digging you believe the assailants to be THE SILHOUETTE]

__MERCENARIES INVOLVED - CODENAMES - STATUS__ <br>
________________________________ - VEILED NIGHTJAR - ACTIVE <br>
________________________________ - FLUSTERED TURKEY - MIA <br>
________________________________  - CRACKED BATFISH - ACTIVE

\*PAAR is the acronym for PUML After Action Report <br>
\*\*As in the explosive kind of mine, it's a pun <br>
\*\*\*Blanchard the Hyperborean was part of the figure skating performance. I love his action movies especially the Copper Cog Warrior series <br>
\*\*\*\*The other two are “Do not kill, harm, or kidnap any other Camera Obscura shutterbugs” and “Non-shutterbug mercenaries, bodyguards, and vigilantes can be eliminated with discretion” <br>
\*\*\*\*\*They say this but I think it was more bad cop/worse cop <br>
\*\*\*\*\*\*More predictable than his spells but take longer apparently <br>
