---
title: "PAAR*: GREEN"
mainfont: Special Elite
---

MISSION <br>
GREENLAND RESEARCH 
**D**RUG **E**XCHANGE on A **B**RIDGE **T**ONIGHT

**MISSION LOCATION** <br> 
█████████████████████████████ ON L’OISE (RIVER), NORTH OF THE FORMER FRENCH CAPITAL PARIS, FRANCE,  ERA (EUROPEAN AND RUSSIAN ALLIANCE)

**MISSION STARTED - MISSION CLOSED** <br> 
2004, 16TH JAN 1990 - 0345, 17TH JAN 1990

**CLIENT - CONTRACT DATE** <br> 
TAG (THE ARROWS OF GAIA)- 16TH JAN 1990

**REMARKS** <br> 


**MERCENARIES INVOLVED - CODENAMES - STATUS** <br> 
████████████████████ - VEILED NIGHTJAR - ACTIVE <br> 
████████████████████ - CRACKED BATFISH - ACTIVE <br>
████████████████████ - FLASHBANG SQUIRREL - KIA <br>
████████████████████ - SIGHTLESS TRUFFLE - ACTIVE <br>
████████████████████ - LANCED BULL - ACTIVE <br>
████████████████████ - BLINK HARE - ACTIVE <br>


Other mission:
NOt sure if I should include the below as a mission I do think it would be good though
Following this an impromptu mission involving transporting a frozen head from Greenland to Cambridge. The team were assaulted by cyborg bears. Wolf crashed their snowmobile into one, but the team soon learnt to kill the riders instead. With the riders gone Truffle led the bears to elks, distracting one and Cracks used their wizardry to pacify the other. With little fanfare they made their delivery.

\*PAAR is the acronym for PUML After Action Report <br> 