---
title: "The Primeval Deities and you episode 1"
mainfont: Courier Prime
---

Overview

Hello listener and welcome to the first episode of The Primeval Deities and you. I am Dr. Harmon Atriti, lecturer of Primeval studies at The University of Cambridge, and your eager host. In this series we will explore the four Primeval deities and their influence on our world. In this episode we will answer a few foundational questions to set us on the correct path.

What are the Primeval Deities? <br>
The Primeval Deities are all encompassing yet mysterious entities. There is no question of their existence and all other deities either do not exist or are inconsequential. 

The Primeval Deities are the sky, earth, water, and life of our reality. They influence us as our collective consciousness shapes them. In this way humanity and divinity entangle as we reach out for one another.

Who are the Primeval Deities? <br>
There are four Primeval Deities. <br>
Nyxmera, the two faced deity of sky and space. An envious and  vicarious being; its eyes the stars, sun, and moons. <br>
Tartarus, the encaged deity of the earth. Its struggles against Nyxmera feed its anger and greed. <br>
Proteus, the free flowing deity of water. It mixes easily with the others and welcomes any and all changes. <br>
Gaia, the unifying entity of life. A charming leader with the nigh impossible goal of uniting the Primeval deities. <br>

When did the Primeval Deities come about? <br>
The whole world learnt of the influence of the Primeval Deities after the 6th of August 1945. This was caused by the first and only atomic bombing of an occupied city, Hiroshima. Whether the deities existed beforehand, or came to be due to the event is in hot debate amongst the academic community.

Who worships the Primeval Deities? <br>
The Biways is primarily an apathetic nation. Although the existence of the Primeval deities is not disputed we, as a nation, do not find benefit in worshipping any of them. Of course there are still some who worship or study the deities in The Biways. <br>
Nyxmera’s admirers are called Suns of Nyxmera. They want to entertain the ever watching Nyxmera and be entertained themselves. Many actors and physics researchers are Suns. The SAE’s, Supreme Asian Empire, and the Mooner’s primary deity is Nyxmera. <br>
Tartarus’ loyalists are called Dotter of Tartarus. They hold personal freedoms as sacrosanct, taking what they can. Many miners and CEOs are Dotters. The CAC’s, Coalition of African Countries, primary deity is Tartarus. <br>
Proteus’ supporters are called Proteans. They are laid back and tend to go with the flow. Many of those working by and on water are Proteans. The ERA’s, The European & Russian Alliance, primary deity is Proteus. <br>
Gaia’s followers are called Gaians. They believe in unification, yet they can’t agree on the method. Gaians tend to work in life or social sciences with many doctors and politicians. The USA’s, United States of America, primary deity is Gaia. <br>
The last super nation, Oceania, has no single primary deity. Instead they worship all the deities and are described as polytheist.

That is a quick introduction to our four Primeval deities. I am eternally grateful for you lending your ears. We will go into detail on all the topics introduced in this episode through the coming months. The next episode will focus on that ever watching deity, Nyxmera. I look forward to seeing you then dear listener.
