---
title: "PuMP*: SIGHTLESS TRUFFLE"
mainfont: Special Elite
---

__BACKGROUND__ <br>
Born and raised in India he witnessed the tumultuous creation of the Supreme Asian Empire (SAE).
He joined the military hoping to keep the peace.
Instead, he found himself as an oppressor.
Many of his friends and family died through regime changes but his monkey, Kiran, was always on his shoulder.
When a Kaiju emerged near the city of Thana he escape into the DOT.
There he found himself as a freedom fighter.

__PHYSICAL FEATURES__ <br>
__Obscure survivalist:__ Always adorned in some form of camo he easily disguises himself in any environment.
He has two defining features: A green headband he'll use to cover his eyes⁂, and Kiran.
Brilliant Kiran is a Crab-eating macaque generally found sleeping in TRUFFLE's ghillie suit.

__PERSONALITY QUIRKS__ <br>
__Alert but overloaded:__ He's vigilant and aware of his surroundings. 
Extremely unlikely to be taken by surprise.
Unfortunately, since his senses are so keen he can be easily overwhelmed, especially by smells. <br>
__Affectionate yet isolated:__ He's incredibly friendly◉.
Being more senior than many of our other members he makes a great teacher.
Due to his past experience in war he never gets too close to anyone♢.

__FAVOURED GEAR__

- Ghillie suit
- Ultimate Iron hollow handle survival knifeΔ
- Ishapore 2A1 bolt-action rifle

__PRIMAL STATS__ <br>
JAWS:0 | EYES:+1 | LIMBS:+2 | NERVES:0

__PRIMAL ABILITIES__ <br>
__Smell-nar^α^:__ He has a remarkable sense of smell and can envision the world with it.
Breaking the law of physics he's able to sense smells that are downwind of his position.
His maximum range is based on the amount of smells, he can only process so much, and physical barriers. <br>
__Hyphae-nated:__ His skin is covered in fungus that can extract nutrients from the ground.
The fungus then shares these nutrients with its host^β^.
This is an incredibly useful ability for hiding in one spot for prolonged periods.

\*PUML Mercenary Profile<br>
⁂Improves his Smell-nar<br>
◉We love watching and chatting about great action movies<br>
♢I know what that's like and I'm glad he at least has Kiran<br>
ΔI'm very envious of this knife. It is an original made for the first Oxbow movie!<br> 
αSmell Navigation And Ranging, like sonar but with smell<br>
βVEILED NIGHTJAR has tried giving the fungus to other people but it only survives on SIGHTLESS TRUFFLE and Kiran<br>