---
title: "PuMP: FLASHBANG FIDDLER"
mainfont: Special Elite
---

__BACKGROUND__ <br>
He was a loyal worker at a paint factory.
The company was developing a new iron based paint for the military when the boss dropped his watch in the vat.
FLASHBANG was ordered to retrieve immediately, not allowed to get gloves.
His arm came out disfigured and the boss fired him for "incompetence".
With no job, anger, and weird powers he joined PUML.

__PHYSICAL FEATURES__ <br>
__Heavy-handed dazzler:__ Dressed in combat clothing of the Biways special forces he would be the most professionally dressed of our mercenaries.
Of course he has to be eccentric instead and use dazzle camouflage*.
The white, black, and red makes him look like a sunburnt zebra.
I guess it slightly distracts from his hematite arm.

__PERSONALITY QUIRKS__ <br>
__Colourful but dull:__ Like paint he's a vivid person, bringing life into any room he enters.
Also like a good paint he's a bit thick.<br>
__Confident yet pathetic:__ When he has his hematite arm he feels invincible and is ready to face any challenge.
Without it he is pathetic.

__FAVOURED GEAR__

- VEER ballistic shield with flash capabilities
- G60 Stun Grenade
- FN Minimi 7.62 Mk3 light machine gun

__PRIMAL STATS__ <br>
JAWS:-1 | EYES:0 | LIMBS:-1 | NERVES:0

__PRIMAL ABILITIES__ <br>
__Munsell sphere:__ He can create a sphere of one colour at any one point he can see.
The sphere reflects light from the chosen colour meaning it can be good cover.
However, it also absorbs the opposite colour⁂ meaning that's the only colour you can see whilst in the sphere.
He can make one to three of these spheres a day each with a maximum diameter of 3 metres.
 <br>
__Hematite arm:__ His left arm, from forearm to hand, is entirely made of a red hematite.
He can use it like a normal arm and hematite is an iron oxide stronger than iron.
However, its more brittle than iron and is easily destroyed.
Thankfully it regrows quickly after an iron rich diet. <br>


\*Used for UK navy ships in WWI, not humans!<br>
⁂according to the Munsell colour system