---
title: "PuMP: CRACKED BATFISH"
mainfont: Special Elite
---

__BACKGROUND__ <br>
He claims to be a time travelling wizard. He’s made tonnes of claims but a few are:

- He was an apprentice sage in Atlantis and escaped as it was sinking
- He shared a picnic on the grey moon with pink mouse like aliens
- He pulled Excalibur out of a rock but exchanged it for some water lilies with the lady of the lake
- He fought a sentient machine that was turning a world of forests into books
- He was tortured by the sanctity of time bureau and dropped in 1974, his time travelling abilities removed

I think he’s so crazy they are either all false or all true.

__PHYSICAL FEATURES__ <br>
__Spaced wizard:__ He dresses like a mage but with modern clothing. Fluffy purple bathrobe, hotel slippers, and a fedora plastered with gold star stickers. He’s surprisingly spry for an emaciated old man. Has a thousand-yard stare, or would that be a thousand-year stare?

__PERSONALITY QUIRKS__ <br>
__Wise but deranged:__ He’s rarely wrong when talking about magic, not that he talks about much else. I should rephrase, it’s the only thing he talks about that seems to make sense, magic being nonsensical in its unnature\*. <br>
__Anarchic yet nihilistic:__ Thankfully for PUML he likes to topple the towers of those who think themselves so high above the rest. Unfortunately he has no care for himself and little for those around him.

__FAVOURED GEAR__

- Hand mirror
- Cat charm with 8 scratch marks
- An unbreakable twig⁂

__PRIMAL STATS__ <br>
JAWS:0 | EYES:-1 | LIMBS:0 | NERVES:+3

__PRIMAL ABILITIES__ <br>
__Sorcery:__ He can cast magic but has no control over what spell he will cast. Supposedly an effect of the time bureau’s limitation they placed on him. <br>
__O-man⏺:__ For whatever reason he seems to cause misfortune/bad luck to those around him. Great when it effects enemies♢.

\*Unnature is to unnatural as nature is to natural; don’t bother looking it up in the dictionary <br>
⁂He claims it can cast magic missiles though he’s cagey about the details and won’t provide a demonstration <br>
⏺As in he’s a man and bad omen, not that he's from Oman <br>
♢Horrible when it effects allies🛆 <br>
🛆Probably deserved when it effects himself <br>
