---
title: "PuMP: SUBSONIC HYDRA"
mainfont: Special Elite
---

__BACKGROUND__ <br>
A cheetah, peregrine falcon, and marlin all in one.
He loves all fast vehicles*, though not spacecrafts.
He's famous in various motor & water sports for his skills and personality.
When testing an experimental vehicle he was chopped in half.
Rather than dieing, he surived and a new him grew from the bottom half.
This has happened a few times.
In this case the top half continued the famous life.
The lower half decided to do something more dangerous and exciting.
He joined PUML*.

__PHYSICAL FEATURES__ <br>
__Blue racer:__ Adorned in racing leathers of cornflower blue.
His jacket and trousers are covered in various sponsor badges*.
He wears a reinforced motorbike helmet covered in a decal of blue and white flames.
A massive pointed metal boot, like a medieval knight wears, encases his left foot.
He wears a normal boot on his right*.

__PERSONALITY QUIRKS__ <br>
**Dependable but arrogant:** Any task or mission I set to him he will carry out with no grumbles.
He's a good mercenary, having picked up all aspects of combat in his training with utmost haste.
I would like to send him on lots of mission to make him better but he thinks he knows everything now.
I fear he'll only learn from disastrous mistakes if at all.
<br>
__Quick yet absent-minded:__ He is a very active and fit person. 
Though exceptionally fast when in action he has a bad tendency to day dream during down time.
Probably a form of energy conservation.

__FAVOURED GEAR__

- Vehicle lock pick kit
- Bag of tungsten carbide ball bearings
- Spectre M4 Submachine gun

__PRIMAL STATS__ <br>
JAWS:0 | EYES:-2 | LIMBS:+2 | NERVES:+1

__PRIMAL ABILITIES__ <br>
**Hydral regeneration:** He has amazing regeneration abilities. 
Small wounds may take minutes but loss of body parts can take months in a coma with nutrient tubes.
Its all because of his incredible stem cells*.
He has two special but identical stem cell producing organs: one in his head the other in his left foot.
If a body part isn't directly connected to one of the organs it won't regenerate.
Strangely his left foot clone will be a perfect clone of the original from when the separation occurred, memories and all.
<br>
**Kinetic transfer:** When touching an item he can increase its speed up to 342m/s*. 
When it leaves his touch this effect stops with the item decelerating normally. 

*Brilliant having someone who can pilot/drive pretty much any vehicle
*He claims its just one of him doing missions for us, i'm sceptical but its hard to tell whether he's being deceitful or just forgetful
*Most prominetly one for PUML
*I've told him this makes his weak points obvious but he pretends to not listen
*Cells that can become various other cells and duplicate a tonne
*343 m/s is the speed of sound, therefore 342m/s and below is subsonic

MG note: SUBSONIC HYDRA will get captured in GREEN and used by Dr. Petra Pufferfish as a source of stem cells for her cloning of her self (these clones having all her memories).
She'll then capture the other hydral clones of SUBSONCI HYDRA (Andrea Dazzi, italian) to harvest their stem cells.